### ISSUE TITLE
clarify the difference between primary and secondary GCs

### ISSUE THREAD

**Issue by examknow** [Libera-Chat/libera-chat.github.io#71] opened 2021-06-01 20:40 UTC

**Comment by jesopo** [comment] 2021-06-01 20:41
I believe there's even been some internal confusion about this, but the clarification I put forward is:

secondary GCs cannot appoint or remove primary GCs, but can appoint secondary GCs.

**Comment by swantzter** [comment] 2021-06-01 20:41
Duplicate of #38

**Closed** 2021-06-01 20:41 UTC
Labels: invalid
